"""Step 9: Case Base Matching & Export - CBR search, XML download, DB save."""

import hashlib
import importlib
import io
import json
import re
import sys
import streamlit as st
import pandas as pd
from generation.step_manager import render_navigation

VALIDATION_POLICY_VERSION = "gen-v5-ttool-tabs-and-reference-refresh"


# -- helpers -----------------------------------------------------------------

def _safe_name(s: str) -> str:
    """Collapse whitespace and strip chars that are illegal in filenames."""
    s = (s or "Untitled").strip()
    s = re.sub(r'[\\/:*?"<>|]+', "_", s)        # illegal path chars - _
    s = re.sub(r"\s+", "_", s)                   # spaces - _
    s = re.sub(r"_+", "_", s).strip("_")         # collapse repeated _
    return s or "Untitled"


def _import_attr(module_name: str, attr_name: str):
    """Retry once if Streamlit hot-reload leaves a partially initialized module."""
    module = importlib.import_module(module_name)
    attr = getattr(module, attr_name, None)
    if attr is not None:
        return attr

    sys.modules.pop(module_name, None)
    module = importlib.import_module(module_name)
    attr = getattr(module, attr_name, None)
    if attr is None:
        raise ImportError(f"cannot import name '{attr_name}' from '{module_name}'")
    return attr


def _build_generation_export_bundle() -> tuple[str, dict, str]:
    """Build base XML, validation result, and enriched TTool export."""
    from cbr_merge import build_ttool_xml, fetch_case_data
    from verification.activity_panel import append_grouped_activity_panels

    reference_payload = st.session_state.get("cbr_kb_case") or None
    top_case = st.session_state.get("cbr_top_case") or {}
    live_case_id = top_case.get("case_id")
    try:
        live_case_id = int(live_case_id) if live_case_id is not None else None
    except (TypeError, ValueError):
        live_case_id = None
    if live_case_id is not None:
        try:
            reference_payload = fetch_case_data(live_case_id)
            st.session_state["cbr_kb_case"] = reference_payload
        except Exception:
            pass

    reference_name = (
        (top_case.get("title"))
        or ((reference_payload or {}).get("system_name"))
        or ""
    )
    reference_panel_name = (
        f"Reference Base Case Diagram - {reference_name}"
        if reference_name else
        "Reference Base Case Diagram"
    )

    base_xml = build_ttool_xml(
        system_name=st.session_state.get("ucd_system_name") or "",
        primary_actors=st.session_state.get("ucd_primary_actors") or [],
        secondary_actors=st.session_state.get("ucd_secondary_actors") or [],
        use_cases=st.session_state.get("ucd_use_cases") or [],
        relationships=st.session_state.get("ucd_relationships") or [],
        generated_panel_name="Use Case Diagram Generated by UCD Master",
        reference_payload=reference_payload,
        reference_panel_name=reference_panel_name,
    )
    validation = _validate_generated_xml_without_relation_checks(base_xml)
    export_xml = append_grouped_activity_panels(base_xml, validation.get("groups") or {})
    return base_xml, validation, export_xml


def _current_export_signature() -> str:
    """Fingerprint the active generation inputs so stale exports are rebuilt."""
    reference_payload = st.session_state.get("cbr_kb_case") or {}
    reference_meta = st.session_state.get("cbr_top_case") or {}
    signature_payload = {
        "version": VALIDATION_POLICY_VERSION,
        "system_name": st.session_state.get("ucd_system_name") or "",
        "primary_actors": st.session_state.get("ucd_primary_actors") or [],
        "secondary_actors": st.session_state.get("ucd_secondary_actors") or [],
        "use_cases": st.session_state.get("ucd_use_cases") or [],
        "relationships": st.session_state.get("ucd_relationships") or [],
        "reference_title": reference_meta.get("title") or "",
        "reference_case_id": reference_meta.get("case_id") or "",
        "reference_payload": {
            "system_name": reference_payload.get("system_name") or "",
            "xml_content": reference_payload.get("xml_content") or "",
            "actors": reference_payload.get("actors") or [],
            "use_cases": reference_payload.get("use_cases") or [],
            "relationships": reference_payload.get("relationships") or [],
        },
    }
    encoded = json.dumps(signature_payload, sort_keys=True, ensure_ascii=True)
    return hashlib.md5(encoded.encode("utf-8")).hexdigest()


def _validate_generated_xml_without_relation_checks(ttool_xml: str) -> dict:
    """Run verification checks on generated XML, skipping relation-type validation."""
    UcdVerificationParser = _import_attr("verification.xml_parser", "UcdVerificationParser")
    element_verification = _import_attr("verification.element_verification", "element_verification")

    uploaded = io.BytesIO(ttool_xml.encode("utf-8"))
    uploaded.name = "generated_ucd.xml"
    parser = UcdVerificationParser(uploaded)
    ucd_dataset = parser.extractData() or []

    action_map = {"Well Written": 0, "Warning!": 1, "Attention Required!": 2}
    rev_action = {v: k for k, v in action_map.items()}

    def _bump(meta, action):
        prev = action_map.get(meta.get("Action", "Well Written"), 0)
        meta["Action"] = rev_action[max(prev, action_map.get(action, 0))]

    for model_dict in ucd_dataset:
        for _, content in model_dict.items():
            for ucd_dict in content.get("Ucd Data", []):
                for ucd_panel_name, details in ucd_dict.items():
                    # Skip the reference diagram — only validate the generated diagram
                    if "reference" in ucd_panel_name.lower():
                        continue
                    primary = details.get("Primary Actors", [])
                    secondary = details.get("Secondary Actors", [])
                    use_cases = details.get("Use Cases", [])
                    connectors = details.get("Connectors", [])
                    system_b = details.get("System Boundary", [])
                    all_actors = primary + secondary
                    sys_name = system_b[0][0] if system_b else ""

                    element_verification.validateActors(all_actors)
                    element_verification.validateUsecases(use_cases)

                    for actor_name, actor_meta in primary:
                        comments, action = element_verification.validateActor(actor_name, "Primary Actor")
                        actor_meta["Comments"].extend(comments)
                        _bump(actor_meta, action)
                    for actor_name, actor_meta in secondary:
                        comments, action = element_verification.validateActor(actor_name, "Secondary Actor")
                        actor_meta["Comments"].extend(comments)
                        _bump(actor_meta, action)
                    for uc_name, uc_meta in use_cases:
                        comments, action = element_verification.validateUsecase(uc_name, sys_name)
                        uc_meta["Comments"].extend(comments)
                        _bump(uc_meta, action)
                    for sys_name_item, sys_meta in system_b:
                        comments, action = element_verification.validateSystem(sys_name_item)
                        sys_meta["Comments"].extend(comments)
                        _bump(sys_meta, action)

                    if system_b:
                        element_verification.validateArrangement(primary, secondary, use_cases, system_b)
                    element_verification.validateActorConnectivity(all_actors, use_cases, connectors)
                    element_verification.validateUsecaseConnectivity(use_cases, all_actors, connectors)

    issues = element_verification.collect_issue_steps(ucd_dataset)
    issue_groups = element_verification.collect_grouped_steps(ucd_dataset)
    issue_groups.pop("Connectors", None)

    errors = sum(1 for issue in issues if issue.startswith("[ERR] "))
    warnings = sum(1 for issue in issues if issue.startswith("[WARN] "))
    if issues == ["No verification issues detected."]:
        errors = 0
        warnings = 0

    return {
        "dataset": ucd_dataset,
        "issues": issues,
        "groups": issue_groups,
        "errors": errors,
        "warnings": warnings,
        "total": errors + warnings,
    }


def _save_to_case_base():
    """Insert the current session's UCD into the case base DB."""
    from connection import connection
    from embeddings import embed_short, embed_paragraph

    system_name    = st.session_state.get("ucd_system_name") or "Untitled"
    paragraph      = st.session_state.get("ucd_paragraph") or ""
    primary_actors = st.session_state.get("ucd_primary_actors") or []
    secondary_actors = st.session_state.get("ucd_secondary_actors") or []
    use_cases      = st.session_state.get("ucd_use_cases") or []
    domains        = st.session_state.get("ucd_domains") or []
    relationships  = st.session_state.get("ucd_relationships") or []

    if not system_name or not use_cases:
        st.warning("Nothing to save - complete the wizard steps first.")
        return

    # Store the enriched export XML so DB records include Requirements and Verification tabs.
    xml_content = st.session_state.get("ucd_ttool_xml")
    if not xml_content:
        base_xml, validation, xml_content = _build_generation_export_bundle()
        st.session_state["ucd_ttool_xml_base"] = base_xml
        st.session_state["ucd_ttool_xml"] = xml_content
        st.session_state["ucd_generation_validation"] = validation
        st.session_state["ucd_generation_export_signature"] = _current_export_signature()
        st.session_state["ucd_generation_validation_hash"] = hashlib.md5(
            base_xml.encode("utf-8")
        ).hexdigest()

    # Inline PlantUML for the DB record
    prim_lines  = "\n".join(f'actor "{a}" as Primary{i+1}' for i, a in enumerate(primary_actors))
    sec_lines   = "\n".join(f'rectangle "{a}" as Secondary{i+1} <<Actor>>' for i, a in enumerate(secondary_actors))
    uc_lines    = "\n".join(f'usecase "{u}" as UC{i+1}' for i, u in enumerate(use_cases))
    plantuml    = (
        "@startuml\n"
        f'rectangle "{system_name}" {{\n{uc_lines}\n}}\n'
        f"{prim_lines}\n{sec_lines}\n@enduml"
    )

    with connection.get_cursor() as cursor:
        # cases
        cursor.execute(
            "INSERT INTO cases "
            "(title, description, title_embedding, description_embedding, domain_json) "
            "VALUES (%s, %s, %s, %s, %s)",
            (
                system_name,
                paragraph,
                embed_short(system_name),
                embed_paragraph(paragraph) if paragraph else embed_short(system_name),
                __import__("json").dumps(domains),
            ),
        )
        case_id = cursor.lastrowid

        # diagrams
        cursor.execute(
            "INSERT INTO diagrams (case_id, system_name, plantuml_code, xml_content) "
            "VALUES (%s, %s, %s, %s)",
            (case_id, system_name, plantuml, xml_content),
        )

        # actors
        for actor in primary_actors:
            cursor.execute(
                "INSERT INTO actors (case_id, actor_name, actor_type, name_embedding) "
                "VALUES (%s, %s, %s, %s)",
                (case_id, actor, "Primary", embed_short(actor)),
            )
        for actor in secondary_actors:
            cursor.execute(
                "INSERT INTO actors "
                "(case_id, actor_name, actor_type, actor_reference_number, name_embedding) "
                "VALUES (%s, %s, %s, %s, %s)",
                (case_id, actor, "Secondary", 703, embed_short(actor)),
            )

        # use_cases (no LLM descriptions - use name as description fallback)
        for uc in use_cases:
            cursor.execute(
                "INSERT INTO use_cases "
                "(case_id, name, description, name_embedding, description_embedding) "
                "VALUES (%s, %s, %s, %s, %s)",
                (case_id, uc, uc, embed_short(uc), embed_short(uc)),
            )

        # relationships
        REL_CODE = {"association": 110, "include": 111, "generalization": 112, "extend": 113}
        for rel in relationships:
            rt  = (rel.get("relationship_type") or "association").lower()
            sn  = rel.get("source_name") or ""
            tn  = rel.get("target_name") or ""
            st_ = rel.get("source_type") or "actor"
            tt  = rel.get("target_type") or "usecase"
            ext = rel.get("extension") or ""
            rc  = REL_CODE.get(rt, 110)
            cursor.execute(
                "INSERT INTO relationships "
                "(relationship_type, relation_code, source_name, target_name, "
                "source_type, target_type, extension, case_id) "
                "VALUES (%s,%s,%s,%s,%s,%s,%s,%s)",
                (rt, rc, sn, tn, st_, tt, ext, case_id),
            )

        # case_domains
        for domain in domains:
            cursor.execute(
                "INSERT INTO case_domains (case_id, domain_name, domain_embedding) "
                "VALUES (%s, %s, %s)",
                (case_id, domain, embed_short(domain)),
            )

        connection.commit()

    st.session_state["_saved_case_id"] = case_id
    st.success(
        f"- Case saved to Case Base! Case ID: **{case_id}** - "
        f"*{system_name}* is now available for future CBR matching."
    )


# -- render -------------------------------------------------------------------

def render():
    st.markdown(
        "Export your completed diagram as TTool-compatible XML "
        "and save it to the knowledge base for future CBR retrieval."
    )

    # -- Summary --------------------------------------------------------------
    with st.expander("Current Diagram Summary", expanded=True):
        col1, col2 = st.columns(2)
        with col1:
            st.write("**System:**",
                     st.session_state.get("ucd_system_name") or "-")
            st.write("**Primary Actors:**",
                     ", ".join(st.session_state.get("ucd_primary_actors") or []) or "-")
            st.write("**Secondary Actors:**",
                     ", ".join(st.session_state.get("ucd_secondary_actors") or []) or "-")
        with col2:
            st.write("**Use Cases:**",
                     ", ".join(st.session_state.get("ucd_use_cases") or []) or "-")
            rels = st.session_state.get("ucd_relationships") or []
            st.write(f"**Relationships:** {len(rels)}")

        col1, col2 = st.columns(2)
        with col1:
            st.write("**System:**",
                     st.session_state.get("ucd_system_name") or "-")
            st.write("**Primary Actors:**",
                     ", ".join(st.session_state.get("ucd_primary_actors") or []) or "-")
            st.write("**Secondary Actors:**",
                     ", ".join(st.session_state.get("ucd_secondary_actors") or []) or "-")
        with col2:
            st.write("**Use Cases:**",
                     ", ".join(st.session_state.get("ucd_use_cases") or []) or "-")
            rels = st.session_state.get("ucd_relationships") or []
            st.write(f"**Relationships:** {len(rels)}")

    st.divider()

    # -- TTool XML Generation & Download --------------------------------------
    st.subheader("TTool XML Export")

    base_xml = st.session_state.get("ucd_ttool_xml_base")
    ttool_xml = st.session_state.get("ucd_ttool_xml")
    validation = st.session_state.get("ucd_generation_validation")

    try:
        current_signature = _current_export_signature()
        stored_signature  = st.session_state.get("ucd_generation_export_signature")
        if current_signature != stored_signature or not ttool_xml:
            with st.spinner("Generating TTool XML with Requirements and Verification tabs..."):
                base_xml, validation, ttool_xml = _build_generation_export_bundle()
            st.session_state["ucd_ttool_xml_base"] = base_xml
            st.session_state["ucd_ttool_xml"] = ttool_xml
            st.session_state["ucd_generation_validation"] = validation
            st.session_state["ucd_generation_export_signature"] = current_signature
    except Exception as _xe:
        st.warning(f"TTool XML generation skipped: {_xe}")
        base_xml = None
        ttool_xml = None

    if ttool_xml:
        from datetime import date
        from verification.ttool_launcher import (
            launch_ttool_with_file,
            save_xml_to_default_downloads,
        )

        sys_name  = st.session_state.get("ucd_system_name") or "Untitled"
        safe_name = _safe_name(sys_name)
        date_str  = date.today().strftime("%Y-%m-%d")
        export_name = f"{safe_name}_ttool_verified_{date_str}.xml"
        st.success(
            "TTool XML ready - generated automatically from your diagram "
            "with Verification and Requirements tabs."
        )
        st.info(
            "Use `Save Session` only to resume the wizard later. "
            "Use the download below for the real TTool XML file that contains "
            "the Verification and Requirements tabs."
        )
        download_clicked = st.download_button(
            "Download TTool UCD XML",
            data=ttool_xml,
            file_name=export_name,
            mime="application/xml",
            use_container_width=True,
            key="btn_ttool_dl",
        )
        if download_clicked:
            default_ttool = "C:\\Users\\mages\\Downloads\\releaseTTool_2_0\\TTool\\ttool_windows.bat"
            ttool_path = st.session_state.get("ttool_path", default_ttool)
            st.session_state["ttool_path"] = ttool_path
            try:
                saved_path = save_xml_to_default_downloads(export_name, ttool_xml)
            except Exception as e:
                st.warning(f"Download started, but the local XML copy could not be saved to Downloads: {e}")
            else:
                ok, msg = launch_ttool_with_file(ttool_path, saved_path)
                if ok:
                    st.info(f"TTool opened with {saved_path}")
                else:
                    st.warning(f"Download started and XML was saved to {saved_path}, but TTool was not opened: {msg}")
        with st.expander("Preview TTool XML", expanded=False):
            st.text_area("TTool XML", value=ttool_xml, height=220,
                         label_visibility="collapsed", key="ttool_preview")
    else:
        st.warning("TTool XML could not be generated.")

    # -- Automatic Validation --------------------------------------------------
    st.divider()
    st.subheader("Automatic Validation Review")
    st.caption(
        "After generation, the diagram is validated automatically for naming, "
        "uniqueness, arrangement, and connectivity. Relationship-type checking "
        "(association/include/extend/generalization) is intentionally skipped here."
    )

    if validation:
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Issues", validation.get("total", 0))
        col2.metric("Errors", validation.get("errors", 0))
        col3.metric("Warnings", validation.get("warnings", 0))

        if validation.get("total", 0) == 0:
            st.success("No non-relationship validation issues were detected in the generated diagram.")
        else:
            st.warning(
                f"Detected **{validation.get('total', 0)}** non-relationship issue(s). "
                "Review them before using the generated diagram downstream."
            )

        with st.expander("Validation Findings", expanded=validation.get("total", 0) > 0):
            issues = validation.get("issues") or []
            for i, issue in enumerate(issues, 1):
                if issue.startswith("[ERR] "):
                    st.markdown(f"**{i}.** :red[{issue}]")
                elif issue.startswith("[WARN] "):
                    st.markdown(f"**{i}.** :orange[{issue}]")
                else:
                    st.markdown(f"**{i}.** {issue}")
    else:
        st.info("Validation results will appear here once the TTool XML is available.")

    st.divider()

    # -- Save to Case Base ----------------------------------------------------
    st.subheader("Save to Case Base")
    already_saved = st.session_state.get("_saved_case_id")
    if already_saved:
        st.info(f"Already saved as Case ID **{already_saved}** this session. "
                "Re-saving will create a duplicate - use only if you changed the diagram.")

    if st.button("Save Case to Database", key="btn_save_db",
                 use_container_width=True, type="primary"):
        try:
            with st.spinner("Saving to case base..."):
                _save_to_case_base()
        except Exception as e:
            st.error(f"Save failed: {e}")

    st.divider()

    # -- SysML v2 Diagram & Download ------------------------------------------
    st.subheader("SysML v2 Use Case Diagram")
    from generation.sysml_ucd import render_sysml_panel
    render_sysml_panel(key="step9")

    # Navigation
    render_navigation(show_next=False)
    st.success("You have completed all steps!")


